SELECT t.GEN, COUNT(t.GEN)
FROM Tabara t
GROUP BY t.GEN;

SELECT t.MEDIU, COUNT(t.MEDIU)
FROM Tabara t
GROUP BY t.MEDIU;

SELECT t.VARSTA, AVG(t.VARSTA), MIN(t.VARSTA), MAX(t.VARSTA)
FROM Tabara t
GROUP BY t.VARSTA; 

SELECT t.BUGET, COUNT(t.BUGET) AS DISTRIBUTIE_BUGET
FROM Tabara t
GROUP BY t.BUGET;

SELECT COUNT(*), SUM(t.BUGET), AVG(t.BUGET), MIN(t.BUGET), MAX(t.BUGET)
FROM Tabara t
WHERE t.BUGET >=700;

SELECT t.GEN, COUNT(*), SUM(t.BUGET), AVG(t.BUGET), MIN(t.BUGET), MAX(t.BUGET)
FROM Tabara t
GROUP BY t.GEN;

SELECT t.MEDIU, COUNT(*), SUM(t.BUGET), AVG(t.BUGET), MIN(t.BUGET), MAX(t.BUGET)
FROM Tabara t
GROUP BY t.MEDIU;

SELECT Alergic
FROM (
		SELECT t.ALERGIC, AVG(t.BUGET)
		FROM Tabara t
		GROUP BY t.ALERGIC 
		ORDER BY t.ALERGIC desc
		LIMIT 1) a;

SELECT t.INFRATIT_CU
FROM Tabara t
GROUP BY t.INFRATIT_CU;
